apiVersion: v2
name: qovery
description: Qovery Helm chart - self managed version
dependencies:
- name: q-storageclass-aws
  condition: services.aws.q-storageclass-aws.enabled
  version: 0.1.0
  repository: file://charts/q-storageclass-aws
- name: q-storageclass-gcp
  condition: services.gcp.q-storageclass-gcp.enabled
  version: 0.1.0
  repository: file://charts/q-storageclass-gcp
- name: q-storageclass-scaleway
  condition: services.scaleway.q-storageclass-scaleway.enabled
  version: 0.1.0
  repository: file://charts/q-storageclass-scaleway
- name: aws-load-balancer-controller
  condition: services.aws.aws-load-balancer-controller.enabled
  version: 1.8.3
  repository: file://charts/aws-load-balancer-controller
- name: ingress-nginx
  condition: services.ingress.ingress-nginx.enabled
  version: 4.11.5
  repository: file://charts/ingress-nginx
- name: external-dns
  condition: services.dns.external-dns.enabled
  version: 8.3.8
  repository: file://charts/external-dns
- name: promtail
  condition: services.logging.promtail.enabled
  version: 6.16.6
  repository: file://charts/promtail
- name: loki
  condition: services.logging.loki.enabled
  version: 5.41.4
  repository: file://charts/loki
- name: cert-manager
  condition: services.certificates.cert-manager.enabled
  version: v1.15.3
  repository: file://charts/cert-manager
- name: cert-manager-configs
  condition: services.certificates.cert-manager-configs.enabled
  version: 0.1.0
  repository: file://charts/cert-manager-configs
- name: qovery-cert-manager-webhook
  condition: services.certificates.qovery-cert-manager-webhook.enabled
  version: 0.1.16
  repository: file://charts/qovery-cert-manager-webhook
- name: metrics-server
  condition: services.observability.metrics-server.enabled
  version: 3.12.1
  repository: file://charts/metrics-server
- name: qovery-cluster-agent
  condition: services.qovery.qovery-cluster-agent.enabled
  version: 0.1.0
  repository: file://charts/qovery-cluster-agent
- name: qovery-shell-agent
  condition: services.qovery.qovery-shell-agent.enabled
  version: 0.1.0
  repository: file://charts/qovery-shell-agent
- name: qovery-engine
  condition: services.qovery.qovery-engine.enabled
  version: 0.0.0
  repository: file://charts/qovery-engine
- name: qovery-priority-class
  condition: services.qovery.qovery-priority-class.enabled
  version: 0.2.0
  repository: file://charts/qovery-priority-class
type: application
version: 1.0.0
appVersion: 1.0.0
home: https://www.qovery.com/
icon: https://raw.githubusercontent.com/Qovery/public-resources/master/qovery_square_new_logo.svg
