apiVersion: v2
name: qovery
description: Qovery Helm chart - self managed version
dependencies:
- name: q-storageclass-aws
  condition: services.aws.q-storageclass-aws.enabled
  version: 0.1.0
  repository: file://charts/q-storageclass-aws
- name: q-storageclass-gcp
  condition: services.gcp.q-storageclass-gcp.enabled
  version: 0.1.0
  repository: file://charts/q-storageclass-gcp
- name: q-storageclass-scaleway
  condition: services.scaleway.q-storageclass-scaleway.enabled
  version: 0.1.0
  repository: file://charts/q-storageclass-scaleway
- name: q-storageclass-azure
  condition: services.azure.q-storageclass-azure.enabled
  version: 0.1.0
  repository: file://charts/q-storageclass-azure
- name: aws-load-balancer-controller
  condition: services.aws.aws-load-balancer-controller.enabled
  version: 3.4.2
  repository: file://charts/aws-load-balancer-controller
- name: gateway-crds-helm
  alias: envoy-gateway-crd
  condition: services.ingress.envoy-gateway-crd.enabled
  version: v1.8.3
  repository: file://charts/envoy-gateway-crd
- name: gateway-helm
  alias: envoy-gateway
  condition: services.ingress.envoy-gateway.enabled
  version: v1.8.3
  repository: file://charts/envoy-gateway
- name: qovery-gateway-class
  condition: services.ingress.qovery-gateway-class.enabled
  version: 0.1.0
  repository: file://charts/qovery-gateway-class
- name: qovery-cluster-gateway
  condition: services.ingress.qovery-cluster-gateway.enabled
  version: 0.1.0
  repository: file://charts/qovery-cluster-gateway
- name: external-dns
  condition: services.dns.external-dns.enabled
  version: 1.21.1
  repository: file://charts/external-dns
- name: alloy
  condition: services.logging.alloy.enabled
  version: 1.10.0
  repository: file://charts/alloy
- name: loki
  condition: services.logging.loki.enabled
  version: 6.55.0
  repository: file://charts/loki
- name: cert-manager
  condition: services.certificates.cert-manager.enabled
  version: v1.20.0
  repository: file://charts/cert-manager
- name: cert-manager-configs
  condition: services.certificates.cert-manager-configs.enabled
  version: 0.1.0
  repository: file://charts/cert-manager-configs
- name: qovery-cert-manager-webhook
  condition: services.certificates.qovery-cert-manager-webhook.enabled
  version: 0.2.0
  repository: file://charts/qovery-cert-manager-webhook
- name: metrics-server
  condition: services.observability.metrics-server.enabled
  version: 3.13.0
  repository: file://charts/metrics-server
- name: qovery-cluster-agent
  condition: services.qovery.qovery-cluster-agent.enabled
  version: 0.1.0
  repository: file://charts/qovery-cluster-agent
- name: qovery-shell-agent
  condition: services.qovery.qovery-shell-agent.enabled
  version: 0.1.0
  repository: file://charts/qovery-shell-agent
- name: qovery-engine
  condition: services.qovery.qovery-engine.enabled
  version: 0.0.0
  repository: file://charts/qovery-engine
- name: qovery-priority-class
  condition: services.qovery.qovery-priority-class.enabled
  version: 0.2.0
  repository: file://charts/qovery-priority-class
type: application
version: 2.0.0
appVersion: 1.0.0
home: https://www.qovery.com/
icon: https://raw.githubusercontent.com/Qovery/public-resources/master/qovery_square_new_logo.svg
