services:
  qovery:
    qovery-cluster-agent:
      enabled: true
    qovery-shell-agent:
      enabled: true
    qovery-engine:
      enabled: false
    qovery-priority-class:
      enabled: true
  ingress:
    ingress-nginx:
      enabled: false
  dns:
    external-dns:
      enabled: false
  logging:
    loki:
      enabled: false
    promtail:
      enabled: false
  certificates:
    cert-manager:
      enabled: false
    cert-manager-configs:
      enabled: false
    qovery-cert-manager-webhook:
      enabled: false
  observability:
    metrics-server:
      enabled: false
  aws:
    q-storageclass-aws:
      enabled: false
    aws-ebs-csi-driver:
      enabled: false
  gcp:
    q-storageclass-gcp:
      enabled: false
  scaleway:
    q-storageclass-scaleway:
      enabled: false
qovery:
  clusterId: '&clusterId set-by-customer'
  clusterShortId: '&clusterShortId set-by-customer'
  organizationId: '&organizationId set-by-customer'
  jwtToken: '&jwtToken set-by-customer'
  domain: '&domain set-by-customer'
  domainWildcard: '&domainWildcard set-by-customer'
  qoveryDnsUrl: '&qoveryDnsUrl set-by-customer'
  lokiUrl: '&lokiUrl set-by-customer'
  promtailLokiUrl: '&promtailLokiUrl set-by-customer'
  acmeEmailAddr: '&acmeEmailAddr set-by-customer'
  externalDnsPrefix: '&externalDnsPrefix set-by-customer'
  architectures: '&architectures set-by-customer'
  engineVersion: '&engineVersion set-by-customer'
  shellAgentVersion: '&shellAgentVersion set-by-customer'
  clusterAgentVersion: '&clusterAgentVersion set-by-customer'
qovery-cluster-agent:
  fullNameOverride: qovery-shell-agent
  image:
    tag: '*clusterAgentVersion'
  environmentVariables:
    CLUSTER_ID: '*clusterId'
    CLUSTER_JWT_TOKEN: '*jwtToken'
    LOKI_URL: '*lokiUrl'
    ORGANIZATION_ID: '*organizationId'
qovery-shell-agent:
  fullNameOverride: qovery-shell-agent
  image:
    tag: '*shellAgentVersion'
  environmentVariables:
    CLUSTER_ID: '*clusterId'
    CLUSTER_JWT_TOKEN: '*jwtToken'
    ORGANIZATION_ID: '*organizationId'
qovery-engine:
  image:
    tag: '*engineVersion'
  engineResources: null
  buildContainer:
    environmentVariables:
      BUILDER_CPU_ARCHITECTURES: '*architectures'
      BUILDER_ROOTLESS_ENABLED: 'true'
  environmentVariables:
    CLUSTER_ID: '*clusterId'
    CLUSTER_JWT_TOKEN: '*jwtToken'
    DOCKER_HOST: tcp://0.0.0.0:2375
    GRPC_SERVER: engine.qovery.com:443
    LIB_ROOT_DIR: /home/qovery/lib
    ORGANIZATION_ID: '*organizationId'
ingress-nginx: {}
external-dns: {}
promtail: {}
loki: {}
cert-manager: {}
qovery-cert-manager-webhook: {}
cert-manager-configs: {}
metrics-server: {}
