# This service account is used to spawn a pod for debugging purposes with admin rights
apiVersion: v1
kind: ServiceAccount
metadata:
  name: qovery-debug
  labels:
    app: qovery-debug
---
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: qovery-debug
  labels:
    app: qovery-debug
rules:
  - apiGroups: ["*"]
    resources: ["*"]
    verbs: ["*"]
#  - nonResourceURLs: ["*"]
#    verbs: ["*"]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: qovery-debug
  labels:
    app: qovery-debug
subjects:
  - kind: ServiceAccount
    name: qovery-debug
roleRef:
  kind: Role
  name: qovery-debug
  apiGroup: rbac.authorization.k8s.io
